
[vml]
	#Smooth rotation mode
	smooth = true
	#Smart mode: Smart direction calculation (minecart hasn't got a usable yaw)
	smart = true
	#SRotation reset treshold
	#Range: 0 ~ 80
	threshold = 8
	#Roller-Coaster mode
	rollercoaster = false
	#Enable on start game
	enablebydefault = true
	#Show debug info in F3 screen
	debug = false

